version: "2"
services:
  web:
    build: ./myreact
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    image: mongo:3.6.4
    ports:
      - "27017:27017"

    api:
      build: ./api
      ports:
        -"5000:5000"
      links:
        - mongo

